name 'rails_app_server'
maintainer 'Tyler Smart'
maintainer_email 'tyler@candlescience.com'
license 'no_rights'
description 'Installs/Configures rails_app_servers'
long_description 'Installs/Configures rails_app_servers'
version '0.1.0'

depends 'application_ruby'
depends 'poise-ruby-build'
depends 'application_git'
depends 'build-essential'
depends 'postgresql'
